Repository accentor/web, pull requests merged in 2020-03, with the labels that each got.

#42 Set up CI
  .github/workflows/ci.yml
Labels: enhancement

#43 Add license
  LICENSE
Labels: chore

#46 Trigger loadData after rescan
  src/store/rescan.js
  src/views/App.vue
Labels: enhancement

#47 Fix missing icons
  src/views/App.vue
Labels: bug

#49 Show empty tracks
  src/components/AlbumActions.vue
  src/components/TrackActions.vue
  src/components/TracksTable.vue
  src/locales/en.json
  src/locales/nl.json
Labels: enhancement

#50 redirect back to main collection after delete on objects page
  src/views/albums/Album.vue
  src/views/artists/Artist.vue
  src/views/genres/Genre.vue
  src/views/labels/Label.vue
  src/views/users/User.vue
Labels: bug

#53 Update on this day when the date changes
  src/store/albums.js
  src/store/store.js
  src/views/App.vue
Labels: bug

#54 Make playlist draggable
  package.json
  src/components/Player.vue
  src/store/player.js
  yarn.lock
Labels: enhancement

#62 Fix new album form
  src/views/albums/NewAlbum.vue
Labels: bug

#60 Allow overriding the base API url via the env
  src/api/base_url.js
Labels: chore

#61 Fix mass edit layout
  src/components/MassEditDialog.vue
Labels: bug

#55 Close tracks if user clicks outside the player
  src/components/Player.vue
Labels: enhancement

#58 Base order on the current length of track_artists
  src/components/MassEditDialog.vue
Labels: bug

#66 Use local time for on this day
  src/store/albums.js
Labels: bug

#67 Make sure getMonth and getDate always have zero padding to compare to iso string
  src/store/albums.js
Labels: bug

#71 Make album and artists cards have a fixed height
  package.json
  src/components/AlbumArtists.vue
  src/components/AlbumCard.vue
  src/components/ArtistCard.vue
  src/sass/main.scss
  yarn.lock
Labels: enhancement
