Repository accentor/web, pull requests merged in 2020-07, with the labels that each got.

#198 Add github actions to dependabot updates
  .github/dependabot.yml
Labels: chore

#181 Add form validations
  src/components/CodecConversionForm.vue
  src/components/CodecForm.vue
  src/components/CoverFilenameForm.vue
  src/components/ImageTypeForm.vue
  src/components/LocationForm.vue
  src/components/MassEditDialog.vue
  src/locales/en.json
  src/locales/nl.json
  src/views/albums/EditAlbum.vue
  src/views/albums/NewAlbum.vue
  src/views/artists/EditArtist.vue
  src/views/artists/NewArtist.vue
  src/views/genres/EditGenre.vue
  src/views/labels/EditLabel.vue
  src/views/settings/Settings.vue
  src/views/tracks/EditTrack.vue
  src/views/users/EditUser.vue
  src/views/users/NewUser.vue
Labels: enhancement

#184 Allow moderators to merge two artists
  src/api/artists.js
  src/components/ArtistActions.vue
  src/components/ArtistMergeDialog.vue
  src/locales/en.json
  src/locales/nl.json
  src/store/albums.js
  src/store/artists.js
  src/store/tracks.js
Labels: enhancement

#203 Fix new user form
  src/views/users/NewUser.vue
Labels: bug

#205 Fix VForm breaking dialog overflow
  src/components/MassEditDialog.vue
Labels: bug

#206 Show long artist and album name with title attr
  src/components/AlbumArtists.vue
  src/components/AlbumCard.vue
  src/components/ArtistCard.vue
Labels: enhancement

#209 Refactor EditArtist and NewArtist to use shared form
  src/components/ArtistForm.vue
  src/views/artists/EditArtist.vue
  src/views/artists/NewArtist.vue
Labels: chore

#208 Refactor EditAlbum and NewAlbum
  src/components/AlbumForm.vue
  src/views/albums/EditAlbum.vue
  src/views/albums/NewAlbum.vue
Labels: bug, chore

#210 Refactor user forms
  src/components/UserForm.vue
  src/views/settings/Settings.vue
  src/views/users/EditUser.vue
  src/views/users/NewUser.vue
Labels: chore

#216 Use vuetify's flex-grow-0 instead of no-grow
  src/Main.vue
  src/components/AlbumForm.vue
  src/components/MassEditDialog.vue
  src/views/tracks/EditTrack.vue
Labels: chore

#215 Move moderator's actions into expand button
  src/components/EditReviewComment.vue
  src/components/TrackActions.vue
  src/locales/en.json
  src/locales/nl.json
Labels: enhancement

#169 Expose tracks merge functionality
  src/api/fetch.js
  src/api/tracks.js
  src/components/TrackActions.vue
  src/components/TracksTable.vue
  src/locales/en.json
  src/locales/nl.json
  src/router.js
  src/store/tracks.js
  src/views/tracks/MergeTrack.vue
Labels: enhancement
