Repository accentor/web, pull requests merged in 2020-06, with the labels that each got.

#116 Improve playlist interactions
  src/components/Player.vue
  src/store/player.js
Labels: enhancement

#75 Expose merging of genres
  src/api/genres.js
  src/components/GenreActions.vue
  src/components/GenreMergeDialog.vue
  src/locales/en.json
  src/store/genres.js
  src/store/tracks.js
Labels: enhancement

#44 Add object to vuex when fetched
  src/api/albums.js
  src/api/artists.js
  src/api/auth_tokens.js
  src/api/codec_conversions.js
  src/api/codecs.js
  src/api/cover_filenames.js
  src/api/fetch.js
  src/api/genres.js
  src/api/image_types.js
  src/api/labels.js
  src/api/locations.js
  src/api/tracks.js
  src/api/users.js
  src/store/actions.js
  src/store/albums.js
  src/store/artists.js
  src/store/auth.js
  src/store/codec_conversions.js
  src/store/codecs.js
  src/store/cover_filenames.js
  src/store/genres.js
  src/store/image_types.js
  src/store/labels.js
  src/store/locations.js
  src/store/tracks.js
  src/store/users.js
Labels: enhancement

#143 Make sure comparing tracks can't fail
  src/comparators.js
  src/store/tracks.js
Labels: bug

#144 Disable edit and destroy while loading
  src/components/AlbumActions.vue
  src/components/ArtistActions.vue
  src/components/GenreActions.vue
  src/components/GenreMergeDialog.vue
  src/components/LabelActions.vue
  src/components/TrackActions.vue
  src/locales/en.json
  src/locales/nl.json
Labels: enhancement

#146 Add missing keys for genre merge
  src/locales/nl.json
Labels: bug

#145 Expose label merge
  src/api/labels.js
  src/components/LabelActions.vue
  src/components/LabelMergeDialog.vue
  src/locales/en.json
  src/locales/nl.json
  src/store/albums.js
  src/store/labels.js
Labels: enhancement

#147 Performance fixes
  src/comparators.js
  src/components/AlbumActions.vue
  src/store/actions.js
  src/store/albums.js
  src/store/artists.js
  src/store/auth.js
  src/store/codec_conversions.js
  src/store/codecs.js
  src/store/cover_filenames.js
  src/store/genres.js
  src/store/image_types.js
  src/store/labels.js
  src/store/locations.js
  src/store/store.js
  src/store/tracks.js
  src/store/users.js
Labels: bug

#149 Provide fallback if object is unavailable
  src/components/TrackArtists.vue
  src/components/TrackGenres.vue
  src/views/albums/Album.vue
Labels: bug

#150 Add actions to genre and label view
  src/views/genres/Genre.vue
  src/views/labels/Label.vue
Labels: enhancement

#151 Revert loading of tracks to before #44
  src/api/tracks.js
  src/store/tracks.js
Labels: bug

#153 Fix typo in compareTracks
  src/comparators.js
Labels: bug

#157 Trigger timeout if rescan is running
  src/store/rescan.js
Labels: enhancement

#155 Fix performance issues
  src/api/tracks.js
  src/store/albums.js
  src/store/artists.js
  src/store/auth.js
  src/store/codec_conversions.js
  src/store/codecs.js
  src/store/cover_filenames.js
  src/store/genres.js
  src/store/image_types.js
  src/store/labels.js
  src/store/locations.js
  src/store/tracks.js
  src/store/users.js
Labels: bug

#166 Use vuetify's click-outside directive
  src/components/Player.vue
Labels: enhancement

#170 Fix reloaded of tracks after mass edit
  src/components/MassEditDialog.vue
Labels: bug

#168 Retry fetch after network error
  package.json
  src/api/fetch.js
  src/api/rescan.js
  yarn.lock
Labels: enhancement

#167 Refactor api calls to generic functions
  src/api/albums.js
  src/api/artists.js
  src/api/auth_tokens.js
  src/api/codec_conversions.js
  src/api/codecs.js
  src/api/cover_filenames.js
  src/api/fetch.js
  src/api/genres.js
  src/api/image_types.js
  src/api/labels.js
  src/api/locations.js
  src/api/tracks.js
  src/api/users.js
Labels: chore

#172 Fix tracks showing up twice for artists that are credited twice
  src/store/tracks.js
Labels: bug

#173 Fix object name in create and update action
  src/api/albums.js
  src/api/artists.js
  src/api/codec_conversions.js
  src/api/codecs.js
  src/api/cover_filenames.js
  src/api/fetch.js
  src/api/genres.js
  src/api/image_types.js
  src/api/labels.js
  src/api/locations.js
  src/api/tracks.js
  src/api/users.js
Labels: bug

#180 Return empty array if artist or genre has no tracks
  src/store/tracks.js
Labels: bug

#179 Fix newAlbum form
  src/views/albums/NewAlbum.vue
Labels: bug

#175 Always use scss as lang for style
  src/Main.vue
  src/components/MassEditDialog.vue
  src/components/TracksTable.vue
  src/views/App.vue
  src/views/Library.vue
  src/views/artists/NewArtist.vue
Labels: chore

#156 Update related objects after destroy
  src/store/albums.js
  src/store/artists.js
  src/store/genres.js
  src/store/labels.js
  src/store/tracks.js
Labels: bug

#182 Add translations for password_confirmation error
  src/locales/en.json
  src/locales/nl.json
Labels: bug

#183 Fix redirect after genre is destroyed
  src/views/genres/Genre.vue
Labels: bug

#185 Fix for loop over array
  src/store/albums.js
  src/store/tracks.js
Labels: bug
