Repository accentor/web, pull requests merged in 2021-07, with the labels that each got.

#525 Update license
  LICENSE
Labels: chore

#285 Create play after track has finished
  src/api/plays.js
  src/components/Player.vue
  src/store/plays.js
  src/store/store.js
Labels: enhancement

#380 Improve reordering of TrackArtists
  src/components/TrackFormArtists.vue
  src/views/tracks/EditTrack.vue
Labels: enhancement

#528 Allow the album to be missing in the TracksTable
  src/components/TracksTable.vue
Labels: bug

#529 Display play count in TracksTable
  src/components/TracksTable.vue
  src/locales/en.json
  src/locales/nl.json
  src/store/plays.js
  src/views/App.vue
Labels: enhancement

#413 (Re)load content on main objects pages
  src/api/albums.js
  src/api/artists.js
  src/api/fetch.js
  src/api/scopes.js
  src/api/tracks.js
  src/router.js
  src/store/actions.js
  src/store/albums.js
  src/store/artists.js
  src/store/tracks.js
  src/views/albums/Album.vue
  src/views/artists/Artist.vue
  src/views/genres/Genre.vue
  src/views/labels/Label.vue
Labels: enhancement

#415 Cache vuex store
  package.json
  src/store/albums.js
  src/store/artists.js
  src/store/genres.js
  src/store/labels.js
  src/store/persistence.js
  src/store/plays.js
  src/store/store.js
  src/store/tracks.js
  yarn.lock
Labels: enhancement

#531 Make sure edit buttons still work after a scope load
  src/store/actions.js
Labels: bug

#530 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#533 Rename merge params to `source_id`
  src/api/artists.js
  src/api/genres.js
  src/api/labels.js
  src/api/tracks.js
Labels: enhancement

#532 Make column widths and alignment in track table a little nicer
  src/components/TracksTable.vue
Labels: enhancement

#536 Remove rescan from localstorage
  src/store/persistence.js
Labels: bug

#535 Limit draggable tracks in Player to handle
  src/components/Player.vue
Labels: bug

#537 Improve grid views on xs screens
  src/components/AlbumActions.vue
  src/components/ArtistActions.vue
  src/components/ArtistMergeDialog.vue
  src/components/EditReviewComment.vue
  src/components/GenreActions.vue
  src/components/GenreMergeDialog.vue
  src/components/LabelActions.vue
  src/components/LabelMergeDialog.vue
  src/views/Home.vue
  src/views/albums/Albums.vue
  src/views/artists/Artist.vue
  src/views/artists/Artists.vue
  src/views/genres/Genres.vue
  src/views/labels/Label.vue
  src/views/labels/Labels.vue
Labels: enhancement

#542 Use `setStartLoading` and `removeOld` for empty scopes
  src/store/actions.js
Labels: bug

#544 Don't wrap track actions
  src/components/TrackActions.vue
Labels: bug

#545 Improve spacing between actions
  src/Main.vue
  src/components/AlbumActions.vue
  src/components/AlbumCard.vue
  src/components/ArtistActions.vue
  src/components/ArtistCard.vue
  src/components/ArtistMergeDialog.vue
  src/components/EditReviewComment.vue
  src/components/GenreActions.vue
  src/components/GenreCard.vue
  src/components/GenreMergeDialog.vue
  src/components/LabelActions.vue
  src/components/LabelCard.vue
  src/components/LabelMergeDialog.vue
  src/components/TrackActions.vue
  src/views/albums/Album.vue
  src/views/artists/Artist.vue
  src/views/genres/Genre.vue
  src/views/labels/Label.vue
Labels: enhancement

#546 Add GitHub action to create a release when a tag is pushed
  .github/release-drafter.yml
  .github/workflows/release.yml
Labels: chore

#547 Run CI actions on pull request and pushes to tags or main branch
  .github/workflows/ci.yml
Labels: chore

#550 Fix double navigation on startup
  src/mixins/Paginated.js
  src/mixins/Searchable.js
Labels: bug

#551 Reset scroll position on navigate
  src/router.js
Labels: bug

#556 Avoid fetching audio for `null` track after last track
  src/components/Player.vue
Labels: bug

#557 Add refactor section to release notes
  .github/release-drafter.yml
Labels: chore

#555 Switch api implementation to `@accentor/api-client-js`
  package.json
  src/api.js
  src/api/albums.js
  src/api/artists.js
  src/api/auth_tokens.js
  src/api/codec_conversions.js
  src/api/codecs.js
  src/api/cover_filenames.js
  src/api/fetch.js
  src/api/genres.js
  src/api/image_types.js
  src/api/labels.js
  src/api/locations.js
  src/api/plays.js
  src/api/rescan.js
  src/api/scopes.js
  src/api/tracks.js
  src/api/users.js
  src/store/albums.js
  src/store/artists.js
  src/store/auth.js
  src/store/codec_conversions.js
  src/store/codecs.js
  src/store/cover_filenames.js
  src/store/genres.js
  src/store/image_types.js
  src/store/labels.js
  src/store/locations.js
  src/store/player.js
  src/store/plays.js
  src/store/rescan.js
  src/store/tracks.js
  src/store/users.js
  src/views/albums/Album.vue
  src/views/artists/Artist.vue
  src/views/genres/Genre.vue
  src/views/labels/Label.vue
  yarn.lock
Labels: refactor
