Repository accentor/web, pull requests merged in 2021-09, with the labels that each got.

#594 Only update `seekTime` from `audio.currentTime` when playing
  src/components/Player.vue
Labels: bug

#595 Fix dependabot review requests
  .github/dependabot.yml
Labels: chore

#598 Load plays for album when visiting album page
  src/store/plays.js
  src/views/albums/Album.vue
Labels: enhancement
